### ISSUE TITLE
Alphabetise labels

### ISSUE THREAD

**Issue by mingard** [edge/logger#11]
Each time labels are logged they appear in a random order. For readability, sorting them alphabetically would help.

**Comment by annybs** [comment]
The magic happens right here: https://github.com/edge/logger/blob/b8b44d057f9b555f2fa1b10063b192de3ae1317f/stdout.go#L54-L60

At the time I wrote this code I didn't grok that maps do not sort deterministically when ranged. I'd be glad to fix this as soon as I have a moment.
